services:
  file-downloader:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    # image: file-downloader:local
    container_name: file-downloader
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
